os:
- linux

language: node_js

node_js:
 - '8'
 - '9'
 - '10'
 - 'node'

before_install:
  - sudo apt-get install libcurl3-dev

before_script:
 - npm install grunt-cli -g
 - npm install express --save

#script:
# - node tests/webserver.js &
# - curl localhost:3000/test.php