os:
- linux

language: node_js

node_js:
 - '8'
 - '9'
 - '10'
 - 'node'

before_script:
 - npm install grunt-cli -g
 - npm install express --save
 - npm install node-curl -g

#script:
# - node tests/webserver.js &
# - curl localhost:3000/test.php