os:
- linux

language: node_js

node_js:
 - 'node'

matrix:
 include:
  - name: 'NodeJS latest / PHP 5.6'
    env: CHANGEPHPENV=5.6
  - name: 'NodeJS latest / PHP 5.6.32'
    env: CHANGEPHPENV=5.6.32
  - name: 'NodeJS latest / PHP 7.0'
    env: CHANGEPHPENV=7.0
  - name: 'NodeJS latest / PHP 7.0.25'
    env: CHANGEPHPENV=7.0.25
  - name: 'NodeJS latest / PHP 7.1'
    env: CHANGEPHPENV=7.1
  - name: 'NodeJS latest / PHP 7.1.11'
    env: CHANGEPHPENV=7.1.11

before_install:
 - phpenv global $CHANGEPHPENV
 - npm i -g npm@v6.2

before_script:
 - npm install git+https://github.com/gruntjs/grunt-contrib-jshint.git
 - npm install grunt-cli -g
 - npm install express --save

script:
 - php --version
 - grunt test