os:
- linux

language: node_js

node_js:
 - 'node'

matrix:
 include:
  - name: 'NodeJS latest / PHP 5.6'
    env: PACKAGENAME=php5.6
    env: CHANGEPHPENV=5.6
  - name: 'NodeJS latest / PHP 5.6.32'
    env: PACKAGENAME=php5.6.32
    env: CHANGEPHPENV=5.6.32
  - name: 'NodeJS latest / PHP 7.0'
    env: PACKAGENAME=php7.0
    env: CHANGEPHPENV=7.0
  - name: 'NodeJS latest / PHP 7.0.25'
    env: PACKAGENAME=php7.0.25
    env: CHANGEPHPENV=7.0.25
  - name: 'NodeJS latest / PHP 7.1'
    env: PACKAGENAME=php7.1
    env: CHANGEPHPENV=7.1
  - name: 'NodeJS latest / PHP 7.1.11'
    env: PACKAGENAME=php7.1.11
    env: CHANGEPHPENV=7.1.11
  - name: 'NodeJS latest / PHP hhvm'
    env: PACKAGENAME=phphhvm
    env: CHANGEPHPENV=hhvm

before_install:
#  # https://askubuntu.com/questions/756181/installing-php-5-6-on-xenial-16-04
#  # Remove all the stock php packages
#  - sudo apt-get purge `dpkg -l | grep php| awk '{print $2}' |tr "\n" " "`
#  # Add the PPA
#  - sudo apt-get install software-properties-common
#  - sudo add-apt-repository -y ppa:ondrej/php
#  # Install your PHP Version
#  - sudo apt-get update
#  - sudo apt-get install $PACKAGENAME
 - phpenv global $CHANGEPHPENV

before_script:
 - npm install grunt-cli -g
 - npm install express --save

script:
 - php --version
 - grunt test