os:
- linux

language: node_js

node_js:
 - 'node'

matrix:
 include:
  - name: 'NodeJS latest / PHP 5.6'
    env: PACKAGENAME=php5.6
  - name: 'NodeJS latest / PHP 7'
    env: PACKAGENAME=php7.0

before_install:
 - sudo apt-get update
 - sudo apt-get install $PACKAGENAME

before_script:
 - npm install grunt-cli -g
 - npm install express --save

script:
 - php --version
 - grunt test